### ISSUE TITLE
invalid input type 

### ISSUE THREAD

**Issue by aminemosbah** [tuttelikz/farabio#41]
## Instructions To Reproduce the Bug

1. What exact command you run:
```
If making changes to the project itself, please use output of the following command:
git rev-parse HEAD; git diff

<put code or diff here>
```
2. __Full logs__ or other relevant observations:
```
<put logs here>
```
3. please simplify the steps as much as possible so they do not require additional resources to run, such as a private dataset.

## Expected behavior:

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

## Environment:

Provide your environment information using the following command:
```
git clone https://gist.github.com/tuttelikz/ebd5ab3ffb29cb9399f2596b8f163a4e a && python a/cenv.py
```

**Comment by aminemosbah** [comment]
## trying to make an inference
test_sets='/content/Test_image'
test = DataLoader(dataset=test_sets, batch_size=1, drop_last=True)
print(f'model {best_model_path} loaded')
with torch.no_grad():
       model_test.eval()
       result=model_test('test')


[/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py](https://localhost:8080/#) in _conv_forward(self, input, weight, bias)
    438                             _pair(0), self.dilation, self.groups)
    439         return F.conv2d(input, weight, bias, self.stride,
--> 440                         self.padding, self.dilation, self.groups)
    441 
    442     def forward(self, input: Tensor) -> Tensor:

TypeError: conv2d() received an invalid combination of arguments - got (str, Parameter, NoneType, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (!str!, !Parameter!, !NoneType!, !tuple!, !tuple!, !tuple!, int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (!str!, !Parameter!, !NoneType!, !tuple!, !tuple!, !tuple!, int)

**Comment by yasmineLalabouali** [comment]
did you solve it ? I'm having the same issue

**Comment by tuttelikz** [comment]
@yasmineLalabouali, let's try to figure it out. Could you please provide a snippet of code you are trying farabio? I need as much details to reproduce.
